# Generated by Django 6.0 on 2026-01-07 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routepoint',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='participants',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('meeting', 'Встреча'), ('party', 'Вечеринка'), ('conference', 'Конференция'), ('training', 'Тренинг'), ('other', 'Другое')], default='meeting', max_length=20, verbose_name='Тип')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания')),
                ('location_type', models.CharField(choices=[('address', 'Адрес'), ('online', 'Онлайн'), ('map', 'Точка на карте')], default='address', max_length=10, verbose_name='Тип места')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('online_link', models.URLField(blank=True, verbose_name='Онлайн-ссылка')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='RoutePoint',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
