# Generated by Django 6.0 on 2026-01-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_expense_expenseparticipant_task_eventparticipant'),
        ('trips', '0004_add_friendship_models'),
    ]

    operations = [
    ]
